# Nome do workflow que será exibido na aba "Actions" do repositório no GitHub.
name: Testar build Docker

# Define os gatilhos (eventos) que iniciarão a execução do workflow.
on:
  # Executa o workflow quando houver um push para a branch "main".
  push:
    branches: [ "main" ]
  
  # Executa também em qualquer pull request aberto contra a branch "main".
  pull_request:

# Define os jobs (tarefas) que serão executados.
jobs:
  # O nome do job é "build".
  build:
    # Especifica que o job deve ser executado em uma máquina virtual com a versão mais recente do Ubuntu.
    runs-on: ubuntu-latest

    # Define os passos (comandos) a serem executados dentro do job.
    steps:
      # 1. Faz o checkout do código do repositório para a máquina virtual.
      # A ação `actions/checkout@v4` é uma ação pré-configurada do GitHub.
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Executa o comando `docker build` para testar se o Dockerfile é válido e funcional.
      # A flag `-t teste-mini-site` nomeia a imagem construída, o que é uma boa prática.
      # O ponto `.` no final indica que o contexto do build é o diretório raiz do repositório.
      - name: Testar build Dockerfile
        run: docker build -t teste-mini-site .
